### ISSUE TITLE
[BUG] <when i change the language to chinese(china), all character turn to garbeld>

### ISSUE THREAD

**Issue by katfionn** [linuxserver/docker-sqlitebrowser#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just like the title said, it all turns to garbeld, i have tried both Chinese(taiwan) and Chinese(China).
![image](https://github.com/linuxserver/docker-sqlitebrowser/assets/136874302/c9427882-a05a-4b37-8adc-bfc5cf03594b)

I have add this file manuelly ***/etc/default/locale***
![image](https://github.com/linuxserver/docker-sqlitebrowser/assets/136874302/e139b8c1-bfbe-4554-bace-cb2fa1724cbd)

### Expected Behavior

lei it show the chinese(china) normally

### Steps To Reproduce

Just like the title said, it all turns to garbeld, i have tried both Chinese(taiwan) and Chinese(China).

### Environment

```markdown
- OS:Armbian based on debian 12
- How docker service was installed: I install it through Casasos, i don't have any knowledge about docker container.
- CPU: RK3566
- devices: Black panter X2
```

### CPU architecture

arm64

### Docker creation

```bash
name: linuxserver-sqlitebrowser
services:
  app:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 3930M
    environment:
      - ENV=LC_ALL zh_CN.UTF-8
      - PGID=1000
      - PUID=1000
      - "RUN=locale-gen zh_CN.UTF-8  "
      - TZ=Asia/Shanghai
    image: linuxserver/sqlitebrowser:latest
    labels:
      icon: https://icon.casaos.io/main/all/sqlitebrowser.png
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 3005
        published: "3005"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/sqlitebrowser/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      ports:
        - container: "3000"
          description:
            en_us: "Container Port: 3000"
      volumes:
        - container: /config
          description:
            en_us: Appdata
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
    container_name: ""
    hostname: ""
networks:
  default:
    name: linuxserver-sqlitebrowser_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: WisdomSky
  category: LinuxServer.io
  description:
    en_us: "Visit homepage: https://hub.docker.com/r/linuxserver/sqlitebrowser/"
  developer: LinuxServer.io
  hostname: ""
  icon: https://icon.casaos.io/main/all/sqlitebrowser.png
  index: /
  main: app
  port_map: "3000"
  project_url: https://sqlitebrowser.org/
  scheme: http
  store_app_id: linuxserver-sqlitebrowser
  tagline:
    en_us: A high quality, visual, open source tool to create, design, and edit
      database files compatible with SQLite.
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sqlitebrowser-banner.png
  title:
    custom: ""
    en_us: Sqlitebrowser
```

### Container logs

```bash
app-1  | [migrations] started
app-1  | [migrations] no migrations found
app-1  | ───────────────────────────────────────
app-1  | 
app-1  |       ██╗     ███████╗██╗ ██████╗
app-1  |       ██║     ██╔════╝██║██╔═══██╗
app-1  |       ██║     ███████╗██║██║   ██║
app-1  |       ██║     ╚════██║██║██║   ██║
app-1  |       ███████╗███████║██║╚██████╔╝
app-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
app-1  | 
app-1  |    Brought to you by linuxserver.io
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | To support the app dev(s) visit:
app-1  | DB Browser for SQLite: https://www.patreon.com/db4s
app-1  | 
app-1  | To support LSIO projects visit:
app-1  | https://www.linuxserver.io/donate/
app-1  | 
app-1  | ───────────────────────────────────────
app-1  | GID/UID
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | User UID:    1000
app-1  | User GID:    1000
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | [custom-init] No custom files found, skipping...
app-1  | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
app-1  | 
app-1  | Xvnc KasmVNC 1.2.0 - built Feb 17 2024 18:51:34
app-1  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
app-1  | See http://kasmweb.com for information on KasmVNC.
app-1  | Underlying X server release 12014000, The X.Org Foundation
app-1  | 
app-1  | [ls.io-init] done.
app-1  | The XKEYBOARD keymap compiler (xkbcomp) reports:
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessEnable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessDisable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessToggle
app-1  | > Warning:          Could not resolve keysym XF86NextElement
app-1  | > Warning:          Could not resolve keysym XF86PreviousElement
app-1  | > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
app-1  | > Warning:          Could not resolve keysym XF86MarkWaypoint
app-1  | > Warning:          Could not resolve keysym XF86Sos
app-1  | > Warning:          Could not resolve keysym XF86NavChart
app-1  | > Warning:          Could not resolve keysym XF86FishingChart
app-1  | > Warning:          Could not resolve keysym XF86SingleRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86DualRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86RadarOverlay
app-1  | > Warning:          Could not resolve keysym XF86TraditionalSonar
app-1  | > Warning:          Could not resolve keysym XF86ClearvuSonar
app-1  | > Warning:          Could not resolve keysym XF86SidevuSonar
app-1  | > Warning:          Could not resolve keysym XF86NavInfo
app-1  | Errors from xkbcomp are not fatal to the X server
app-1  | Obt-Message: Xinerama extension is not present on the server
app-1  | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
app-1  | MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
app-1  | libEGL warning: egl: failed to create dri2 screen
app-1  |  2024-02-26 12:03:59,833 [INFO] websocket 0: got client connection from 127.0.0.1
app-1  |  2024-02-26 12:03:59,886 [PRIO] Connections: accepted: @183.6.114.242_1708920239.834383::websocket
app-1  | node:internal/process/promises:289
app-1  |             triggerUncaughtException(err, true /* fromPromise */);
app-1  |             ^
app-1  | 
app-1  | [Error: EACCES: permission denied, mkdir '/etc/locale'] {
app-1  |   errno: -13,
app-1  |   code: 'EACCES',
app-1  |   syscall: 'mkdir',
app-1  |   path: '/etc/locale'
app-1  | }
app-1  | 
app-1  | Node.js v20.11.1
app-1  | node:internal/process/promises:289
app-1  |             triggerUncaughtException(err, true /* fromPromise */);
app-1  |             ^
app-1  | 
app-1  | [Error: EACCES: permission denied, mkdir '/etc/locale'] {
app-1  |   errno: -13,
app-1  |   code: 'EACCES',
app-1  |   syscall: 'mkdir',
app-1  |   path: '/etc/locale'
app-1  | }
app-1  | 
app-1  | Node.js v20.11.1
app-1  |  2024-02-26 12:34:47,895 [PRIO] Connections: closed: @183.6.114.242_1708920239.834383::websocket (Clean disconnection)
app-1  | X connection to :1 broken (explicit kill or server shutdown).
app-1  | The X11 connection broke (error 1). Did the X11 server die?
app-1  | [migrations] started
app-1  | [migrations] no migrations found
app-1  | usermod: no changes
app-1  | ───────────────────────────────────────
app-1  | 
app-1  |       ██╗     ███████╗██╗ ██████╗
app-1  |       ██║     ██╔════╝██║██╔═══██╗
app-1  |       ██║     ███████╗██║██║   ██║
app-1  |       ██║     ╚════██║██║██║   ██║
app-1  |       ███████╗███████║██║╚██████╔╝
app-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
app-1  | 
app-1  |    Brought to you by linuxserver.io
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | To support the app dev(s) visit:
app-1  | DB Browser for SQLite: https://www.patreon.com/db4s
app-1  | 
app-1  | To support LSIO projects visit:
app-1  | https://www.linuxserver.io/donate/
app-1  | 
app-1  | ───────────────────────────────────────
app-1  | GID/UID
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | User UID:    1000
app-1  | User GID:    1000
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | [custom-init] No custom files found, skipping...
app-1  | _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
app-1  | 
app-1  | Xvnc KasmVNC 1.2.0 - built Feb 17 2024 18:51:34
app-1  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
app-1  | See http://kasmweb.com for information on KasmVNC.
app-1  | Underlying X server release 12014000, The X.Org Foundation
app-1  | 
app-1  | [ls.io-init] done.
app-1  | The XKEYBOARD keymap compiler (xkbcomp) reports:
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessEnable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessDisable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessToggle
app-1  | > Warning:          Could not resolve keysym XF86NextElement
app-1  | > Warning:          Could not resolve keysym XF86PreviousElement
app-1  | > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
app-1  | > Warning:          Could not resolve keysym XF86MarkWaypoint
app-1  | > Warning:          Could not resolve keysym XF86Sos
app-1  | > Warning:          Could not resolve keysym XF86NavChart
app-1  | > Warning:          Could not resolve keysym XF86FishingChart
app-1  | > Warning:          Could not resolve keysym XF86SingleRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86DualRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86RadarOverlay
app-1  | > Warning:          Could not resolve keysym XF86TraditionalSonar
app-1  | > Warning:          Could not resolve keysym XF86ClearvuSonar
app-1  | > Warning:          Could not resolve keysym XF86SidevuSonar
app-1  | > Warning:          Could not resolve keysym XF86NavInfo
app-1  | Errors from xkbcomp are not fatal to the X server
app-1  | Obt-Message: Xinerama extension is not present on the server
app-1  | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
app-1  | MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
app-1  | libEGL warning: egl: failed to create dri2 screen
app-1  | X connection to :1 broken (explicit kill or server shutdown).
app-1  | The X11 connection broke (error 1). Did the X11 server die?
app-1  | [migrations] started
app-1  | [migrations] no migrations found
app-1  | usermod: no changes
app-1  | ───────────────────────────────────────
app-1  | 
app-1  |       ██╗     ███████╗██╗ ██████╗
app-1  |       ██║     ██╔════╝██║██╔═══██╗
app-1  |       ██║     ███████╗██║██║   ██║
app-1  |       ██║     ╚════██║██║██║   ██║
app-1  |       ███████╗███████║██║╚██████╔╝
app-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
app-1  | 
app-1  |    Brought to you by linuxserver.io
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | To support the app dev(s) visit:
app-1  | DB Browser for SQLite: https://www.patreon.com/db4s
app-1  | 
app-1  | To support LSIO projects visit:
app-1  | https://www.linuxserver.io/donate/
app-1  | 
app-1  | ───────────────────────────────────────
app-1  | GID/UID
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | User UID:    1000
app-1  | User GID:    1000
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | [custom-init] No custom files found, skipping...
app-1  | _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
app-1  | 
app-1  | Xvnc KasmVNC 1.2.0 - built Feb 17 2024 18:51:34
app-1  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
app-1  | See http://kasmweb.com for information on KasmVNC.
app-1  | Underlying X server release 12014000, The X.Org Foundation
app-1  | 
app-1  | [ls.io-init] done.
app-1  | The XKEYBOARD keymap compiler (xkbcomp) reports:
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessEnable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessDisable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessToggle
app-1  | > Warning:          Could not resolve keysym XF86NextElement
app-1  | > Warning:          Could not resolve keysym XF86PreviousElement
app-1  | > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
app-1  | > Warning:          Could not resolve keysym XF86MarkWaypoint
app-1  | > Warning:          Could not resolve keysym XF86Sos
app-1  | > Warning:          Could not resolve keysym XF86NavChart
app-1  | > Warning:          Could not resolve keysym XF86FishingChart
app-1  | > Warning:          Could not resolve keysym XF86SingleRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86DualRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86RadarOverlay
app-1  | > Warning:          Could not resolve keysym XF86TraditionalSonar
app-1  | > Warning:          Could not resolve keysym XF86ClearvuSonar
app-1  | > Warning:          Could not resolve keysym XF86SidevuSonar
app-1  | > Warning:          Could not resolve keysym XF86NavInfo
app-1  | Errors from xkbcomp are not fatal to the X server
app-1  | Obt-Message: Xinerama extension is not present on the server
app-1  | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
app-1  | MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
app-1  | libEGL warning: egl: failed to create dri2 screen
app-1  |  2024-02-26 12:35:21,503 [INFO] websocket 0: got client connection from 127.0.0.1
app-1  |  2024-02-26 12:35:21,553 [PRIO] Connections: accepted: @183.6.114.242_1708922121.504574::websocket
```

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-sqlitebrowser?tab=readme-ov-file#language-support---internationalization

**Comment by katfionn** [comment]
> https://github.com/linuxserver/docker-sqlitebrowser?tab=readme-ov-file#language-support---internationalization

![image](https://github.com/linuxserver/docker-sqlitebrowser/assets/136874302/d69e40d3-9183-411e-b9bd-421c9e65b4f4)

here are the everything i have tried, and it's not solve my problem yet. Also, iave tried two different broswer to open it.

and here is the now log below:

---

`app-1  | [migrations] started
app-1  | [migrations] no migrations found
app-1  | ───────────────────────────────────────
app-1  | 
app-1  |       ██╗     ███████╗██╗ ██████╗
app-1  |       ██║     ██╔════╝██║██╔═══██╗
app-1  |       ██║     ███████╗██║██║   ██║
app-1  |       ██║     ╚════██║██║██║   ██║
app-1  |       ███████╗███████║██║╚██████╔╝
app-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
app-1  | 
app-1  |    Brought to you by linuxserver.io
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | To support the app dev(s) visit:
app-1  | DB Browser for SQLite: https://www.patreon.com/db4s
app-1  | 
app-1  | To support LSIO projects visit:
app-1  | https://www.linuxserver.io/donate/
app-1  | 
app-1  | ───────────────────────────────────────
app-1  | GID/UID
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | User UID:    1000
app-1  | User GID:    1000
app-1  | ───────────────────────────────────────
app-1  | 
app-1  | [custom-init] No custom files found, skipping...
app-1  | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
app-1  | 
app-1  | Xvnc KasmVNC 1.2.0 - built Feb 17 2024 18:51:34
app-1  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
app-1  | See http://kasmweb.com for information on KasmVNC.
app-1  | Underlying X server release 12014000, The X.Org Foundation
app-1  | 
app-1  | [ls.io-init] done.
app-1  | The XKEYBOARD keymap compiler (xkbcomp) reports:
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessEnable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessDisable
app-1  | > Warning:          Could not resolve keysym XF86CameraAccessToggle
app-1  | > Warning:          Could not resolve keysym XF86NextElement
app-1  | > Warning:          Could not resolve keysym XF86PreviousElement
app-1  | > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
app-1  | > Warning:          Could not resolve keysym XF86MarkWaypoint
app-1  | > Warning:          Could not resolve keysym XF86Sos
app-1  | > Warning:          Could not resolve keysym XF86NavChart
app-1  | > Warning:          Could not resolve keysym XF86FishingChart
app-1  | > Warning:          Could not resolve keysym XF86SingleRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86DualRangeRadar
app-1  | > Warning:          Could not resolve keysym XF86RadarOverlay
app-1  | > Warning:          Could not resolve keysym XF86TraditionalSonar
app-1  | > Warning:          Could not resolve keysym XF86ClearvuSonar
app-1  | > Warning:          Could not resolve keysym XF86SidevuSonar
app-1  | > Warning:          Could not resolve keysym XF86NavInfo
app-1  | Errors from xkbcomp are not fatal to the X server
app-1  | Obt-Message: Xinerama extension is not present on the server
app-1  | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
app-1  | MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
app-1  | libEGL warning: egl: failed to create dri2 screen
app-1  |  2024-02-26 13:33:53,840 [INFO] websocket 0: got client connection from 127.0.0.1
app-1  |  2024-02-26 13:33:53,889 [PRIO] Connections: accepted: @183.6.114.242_1708925633.841620::websocket
app-1  |  2024-02-26 13:34:57,549 [PRIO] Connections: closed: @183.6.114.242_1708925633.841620::websocket (Clean disconnection)
app-1  |  2024-02-26 13:35:12,332 [INFO] websocket 1: got client connection from 127.0.0.1
app-1  |  2024-02-26 13:35:12,390 [PRIO] Connections: accepted: @183.6.114.242_1708925712.334483::websocket`

**Comment by katfionn** [comment]
> > https://github.com/linuxserver/docker-sqlitebrowser?tab=readme-ov-file#language-support---internationalization
> 
> ![image](https://private-user-images.githubusercontent.com/136874302/307674897-d69e40d3-9183-411e-b9bd-421c9e65b4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjYxNzgsIm5iZiI6MTcwODkyNTg3OCwicGF0aCI6Ii8xMzY4NzQzMDIvMzA3Njc0ODk3LWQ2OWU0MGQzLTkxODMtNDExZS1iOWJkLTQyMWM5ZTY1YjRmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDI2MTcyMWNiNWZhNGRkNjliNWFmZDFjN2ZmZWY3MDYwNzBlNGFhNWQyMzMxMGViMDhkMzVmY2YwYzYyYjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l7dOHoboMmq2ECR5yUJHsyelvtPpgicgyg4dCrOqn1E)
> 
> here are the everything i have tried, and it's not solve my problem yet. Also, iave tried two different broswer to open it.
> 
> and here is the now log below:
> 
> ```
> app-1  | [migrations] started
> app-1  | [migrations] no migrations found
> app-1  | ───────────────────────────────────────
> app-1  | 
> app-1  |       ██╗     ███████╗██╗ ██████╗
> app-1  |       ██║     ██╔════╝██║██╔═══██╗
> app-1  |       ██║     ███████╗██║██║   ██║
> app-1  |       ██║     ╚════██║██║██║   ██║
> app-1  |       ███████╗███████║██║╚██████╔╝
> app-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
> app-1  | 
> app-1  |    Brought to you by linuxserver.io
> app-1  | ───────────────────────────────────────
> app-1  | 
> app-1  | To support the app dev(s) visit:
> app-1  | DB Browser for SQLite: https://www.patreon.com/db4s
> app-1  | 
> app-1  | To support LSIO projects visit:
> app-1  | https://www.linuxserver.io/donate/
> app-1  | 
> app-1  | ───────────────────────────────────────
> app-1  | GID/UID
> app-1  | ───────────────────────────────────────
> app-1  | 
> app-1  | User UID:    1000
> app-1  | User GID:    1000
> app-1  | ───────────────────────────────────────
> app-1  | 
> app-1  | [custom-init] No custom files found, skipping...
> app-1  | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> app-1  | 
> app-1  | Xvnc KasmVNC 1.2.0 - built Feb 17 2024 18:51:34
> app-1  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
> app-1  | See http://kasmweb.com for information on KasmVNC.
> app-1  | Underlying X server release 12014000, The X.Org Foundation
> app-1  | 
> app-1  | [ls.io-init] done.
> app-1  | The XKEYBOARD keymap compiler (xkbcomp) reports:
> app-1  | > Warning:          Could not resolve keysym XF86CameraAccessEnable
> app-1  | > Warning:          Could not resolve keysym XF86CameraAccessDisable
> app-1  | > Warning:          Could not resolve keysym XF86CameraAccessToggle
> app-1  | > Warning:          Could not resolve keysym XF86NextElement
> app-1  | > Warning:          Could not resolve keysym XF86PreviousElement
> app-1  | > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> app-1  | > Warning:          Could not resolve keysym XF86MarkWaypoint
> app-1  | > Warning:          Could not resolve keysym XF86Sos
> app-1  | > Warning:          Could not resolve keysym XF86NavChart
> app-1  | > Warning:          Could not resolve keysym XF86FishingChart
> app-1  | > Warning:          Could not resolve keysym XF86SingleRangeRadar
> app-1  | > Warning:          Could not resolve keysym XF86DualRangeRadar
> app-1  | > Warning:          Could not resolve keysym XF86RadarOverlay
> app-1  | > Warning:          Could not resolve keysym XF86TraditionalSonar
> app-1  | > Warning:          Could not resolve keysym XF86ClearvuSonar
> app-1  | > Warning:          Could not resolve keysym XF86SidevuSonar
> app-1  | > Warning:          Could not resolve keysym XF86NavInfo
> app-1  | Errors from xkbcomp are not fatal to the X server
> app-1  | Obt-Message: Xinerama extension is not present on the server
> app-1  | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
> app-1  | MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
> app-1  | libEGL warning: egl: failed to create dri2 screen
> app-1  |  2024-02-26 13:33:53,840 [INFO] websocket 0: got client connection from 127.0.0.1
> app-1  |  2024-02-26 13:33:53,889 [PRIO] Connections: accepted: @183.6.114.242_1708925633.841620::websocket
> app-1  |  2024-02-26 13:34:57,549 [PRIO] Connections: closed: @183.6.114.242_1708925633.841620::websocket (Clean disconnection)
> app-1  |  2024-02-26 13:35:12,332 [INFO] websocket 1: got client connection from 127.0.0.1
> app-1  |  2024-02-26 13:35:12,390 [PRIO] Connections: accepted: @183.6.114.242_1708925712.334483::websocket
> ```

---

thanks for replying me

**Comment by thelamer** [comment]
The readme gives you all the env bars you need 
```
-e DOCKER_MODS=linuxserver/mods:universal-package-install
-e INSTALL_PACKAGES=font-noto-cjk
-e LC_ALL=zh_CN.UTF-8
```

**Comment by katfionn** [comment]
> The readme gives you all the env bars you need
> 
> ```
> -e DOCKER_MODS=linuxserver/mods:universal-package-install
> -e INSTALL_PACKAGES=font-noto-cjk
> -e LC_ALL=zh_CN.UTF-8
> ```

Should i fill the form like this?
![image](https://github.com/linuxserver/docker-sqlitebrowser/assets/136874302/db390616-ddfd-4ef0-9fed-e18f99e1d515)

Each tiem i saved it and restart the containner, these two enviroment command will dissapper
```
ENV DOCKER_MODS=linuxserver/mods:universal-package-install
ENV INSTALL_PACKAGES=font-noto-cjk
```
like this 
![image](https://github.com/linuxserver/docker-sqlitebrowser/assets/136874302/ff1dc17c-f550-4a76-9ecb-e4a78813c4f6)

I do really know nothing about the docker, any further helps will be greatful.

**Comment by thelamer** [comment]
I don't know what this app is, but you just need to be able to pass multiple env variables to it which should be possible. Here is my docker run command for testing: 

```
docker run --rm -it \
  -e DOCKER_MODS=linuxserver/mods:universal-package-install \
  -e INSTALL_PACKAGES=font-noto-cjk \
  -e LC_ALL=zh_CN.UTF-8 \
  -p 3000:3000 \
  linuxserver/sqlitebrowser bash
```

I can assure you it does work, you just need to figure out how to pass multiple env vars from that interface: 

![chinese](https://github.com/linuxserver/docker-sqlitebrowser/assets/1852688/f8f2b547-8f5d-4e5b-8378-59e0f2829cf7)

**Comment by katfionn** [comment]
> I don't know what this app is, but you just need to be able to pass multiple env variables to it which should be possible. Here is my docker run command for testing:
> 
> ```
> docker run --rm -it \
>   -e DOCKER_MODS=linuxserver/mods:universal-package-install \
>   -e INSTALL_PACKAGES=font-noto-cjk \
>   -e LC_ALL=zh_CN.UTF-8 \
>   -p 3000:3000 \
>   linuxserver/sqlitebrowser bash
> ```
> 
> I can assure you it does work, you just need to figure out how to pass multiple env vars from that interface:
> 
> ![chinese](https://private-user-images.githubusercontent.com/1852688/307849051-f8f2b547-8f5d-4e5b-8378-59e0f2829cf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjY1NDUsIm5iZiI6MTcwODk2NjI0NSwicGF0aCI6Ii8xODUyNjg4LzMwNzg0OTA1MS1mOGYyYjU0Ny04ZjVkLTRlNWItODM3OC01OWUwZjI4MjljZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTY1MDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM5ZjRhNzVhM2VlMTA1N2I0MzkxOTllYzZjM2Q4YWMxY2Y2ZWM3YTJjYTQyNjYyZDc1MDY4YmY2ZGViY2NjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CxSfIxKrMp7Av62IlruFDc53QpLGTaRfBRsjikyLriQ)

yep! It's very awkward, after i tried last time, it doesn't work for few hours, then after i got off work, it's about five or six hours later, it actually worked! It's my bad that i've been impatient. Thanks you a lot!❤

And the last time i tried, i found it should be filled like this:
![图片](https://github.com/linuxserver/docker-sqlitebrowser/assets/136874302/a86bbefc-4627-4a02-9d6d-69f5cb0cf247)
